### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Timmytimi** [ITXiaoPang/infinity2wetab#2]
报错以后显示这个
Traceback (most recent call last):
  File "C:\Users\XXX\Downloads\main.py", line 57, in <module>
    _infinty_folders = load_infinty()
  File "C:\Users\XXX\Downloads\main.py", line 7, in load_infinty
    d_infinity = json.load(f_infinity)
  File "D:\Python312\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 1950: illegal multibyte sequence
![image](https://github.com/ITXiaoPang/infinity2wetab/assets/71446980/d18410db-efbb-4bed-a6a8-04f5e6203efe)

**Comment by ITXiaoPang** [comment]
我这边没有Windows环境，我用的都是UTF-8编码，你可以试试在每个open函数加个参数encoding='gbk'指定gbk编码试试，类似open('infinityBackup.infinity', 'r',encoding='gbk')

**Comment by Timmytimi** [comment]
win上加了参数还是不行，不过我在macos上成功了，感谢，你可以在readme写一下仅适用macos

**Comment by ITXiaoPang** [comment]
客气了，解决了就好，这个报错本质是编码问题，在win上保存成utf8应该也是可以解决的，还是很感谢提供信息
